---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-bedrockagent-reader
  namespace: default
rules:
- apiGroups:
  - bedrockagent.services.k8s.aws
  resources:
  - agents
  - knowledgebases
  verbs:
  - get
  - list
  - watch
