// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type ActionGroupSignature string

const (
	ActionGroupSignature_AMAZON_CodeInterpreter ActionGroupSignature = "AMAZON.CodeInterpreter"
	ActionGroupSignature_AMAZON_UserInput       ActionGroupSignature = "AMAZON.UserInput"
)

type ActionGroupState string

const (
	ActionGroupState_DISABLED ActionGroupState = "DISABLED"
	ActionGroupState_ENABLED  ActionGroupState = "ENABLED"
)

type AgentAliasStatus string

const (
	AgentAliasStatus_CREATING AgentAliasStatus = "CREATING"
	AgentAliasStatus_DELETING AgentAliasStatus = "DELETING"
	AgentAliasStatus_FAILED   AgentAliasStatus = "FAILED"
	AgentAliasStatus_PREPARED AgentAliasStatus = "PREPARED"
	AgentAliasStatus_UPDATING AgentAliasStatus = "UPDATING"
)

type AgentStatus_SDK string

const (
	AgentStatus_SDK_CREATING     AgentStatus_SDK = "CREATING"
	AgentStatus_SDK_DELETING     AgentStatus_SDK = "DELETING"
	AgentStatus_SDK_FAILED       AgentStatus_SDK = "FAILED"
	AgentStatus_SDK_NOT_PREPARED AgentStatus_SDK = "NOT_PREPARED"
	AgentStatus_SDK_PREPARED     AgentStatus_SDK = "PREPARED"
	AgentStatus_SDK_PREPARING    AgentStatus_SDK = "PREPARING"
	AgentStatus_SDK_UPDATING     AgentStatus_SDK = "UPDATING"
	AgentStatus_SDK_VERSIONING   AgentStatus_SDK = "VERSIONING"
)

type ChunkingStrategy string

const (
	ChunkingStrategy_FIXED_SIZE   ChunkingStrategy = "FIXED_SIZE"
	ChunkingStrategy_HIERARCHICAL ChunkingStrategy = "HIERARCHICAL"
	ChunkingStrategy_NONE         ChunkingStrategy = "NONE"
	ChunkingStrategy_SEMANTIC     ChunkingStrategy = "SEMANTIC"
)

type ConfluenceAuthType string

const (
	ConfluenceAuthType_BASIC                     ConfluenceAuthType = "BASIC"
	ConfluenceAuthType_OAUTH2_CLIENT_CREDENTIALS ConfluenceAuthType = "OAUTH2_CLIENT_CREDENTIALS"
)

type ConfluenceHostType string

const (
	ConfluenceHostType_SAAS ConfluenceHostType = "SAAS"
)

type ContentDataSourceType string

const (
	ContentDataSourceType_CUSTOM ContentDataSourceType = "CUSTOM"
	ContentDataSourceType_S3     ContentDataSourceType = "S3"
)

type ConversationRole string

const (
	ConversationRole_assistant ConversationRole = "assistant"
	ConversationRole_user      ConversationRole = "user"
)

type CrawlFilterConfigurationType string

const (
	CrawlFilterConfigurationType_PATTERN CrawlFilterConfigurationType = "PATTERN"
)

type CreationMode string

const (
	CreationMode_DEFAULT    CreationMode = "DEFAULT"
	CreationMode_OVERRIDDEN CreationMode = "OVERRIDDEN"
)

type CustomControlMethod string

const (
	CustomControlMethod_RETURN_CONTROL CustomControlMethod = "RETURN_CONTROL"
)

type CustomSourceType string

const (
	CustomSourceType_IN_LINE     CustomSourceType = "IN_LINE"
	CustomSourceType_S3_LOCATION CustomSourceType = "S3_LOCATION"
)

type DataDeletionPolicy string

const (
	DataDeletionPolicy_DELETE DataDeletionPolicy = "DELETE"
	DataDeletionPolicy_RETAIN DataDeletionPolicy = "RETAIN"
)

type DataSourceStatus string

const (
	DataSourceStatus_AVAILABLE           DataSourceStatus = "AVAILABLE"
	DataSourceStatus_DELETE_UNSUCCESSFUL DataSourceStatus = "DELETE_UNSUCCESSFUL"
	DataSourceStatus_DELETING            DataSourceStatus = "DELETING"
)

type DataSourceType string

const (
	DataSourceType_CONFLUENCE DataSourceType = "CONFLUENCE"
	DataSourceType_CUSTOM     DataSourceType = "CUSTOM"
	DataSourceType_S3         DataSourceType = "S3"
	DataSourceType_SALESFORCE DataSourceType = "SALESFORCE"
	DataSourceType_SHAREPOINT DataSourceType = "SHAREPOINT"
	DataSourceType_WEB        DataSourceType = "WEB"
)

type DocumentStatus string

const (
	DocumentStatus_DELETE_IN_PROGRESS         DocumentStatus = "DELETE_IN_PROGRESS"
	DocumentStatus_DELETING                   DocumentStatus = "DELETING"
	DocumentStatus_FAILED                     DocumentStatus = "FAILED"
	DocumentStatus_IGNORED                    DocumentStatus = "IGNORED"
	DocumentStatus_INDEXED                    DocumentStatus = "INDEXED"
	DocumentStatus_IN_PROGRESS                DocumentStatus = "IN_PROGRESS"
	DocumentStatus_METADATA_PARTIALLY_INDEXED DocumentStatus = "METADATA_PARTIALLY_INDEXED"
	DocumentStatus_METADATA_UPDATE_FAILED     DocumentStatus = "METADATA_UPDATE_FAILED"
	DocumentStatus_NOT_FOUND                  DocumentStatus = "NOT_FOUND"
	DocumentStatus_PARTIALLY_INDEXED          DocumentStatus = "PARTIALLY_INDEXED"
	DocumentStatus_PENDING                    DocumentStatus = "PENDING"
	DocumentStatus_STARTING                   DocumentStatus = "STARTING"
)

type EmbeddingDataType string

const (
	EmbeddingDataType_BINARY  EmbeddingDataType = "BINARY"
	EmbeddingDataType_FLOAT32 EmbeddingDataType = "FLOAT32"
)

type FlowConnectionType string

const (
	FlowConnectionType_Conditional FlowConnectionType = "Conditional"
	FlowConnectionType_Data        FlowConnectionType = "Data"
)

type FlowNodeIODataType string

const (
	FlowNodeIODataType_Array   FlowNodeIODataType = "Array"
	FlowNodeIODataType_Boolean FlowNodeIODataType = "Boolean"
	FlowNodeIODataType_Number  FlowNodeIODataType = "Number"
	FlowNodeIODataType_Object  FlowNodeIODataType = "Object"
	FlowNodeIODataType_String  FlowNodeIODataType = "String"
)

type FlowNodeType string

const (
	FlowNodeType_Agent          FlowNodeType = "Agent"
	FlowNodeType_Collector      FlowNodeType = "Collector"
	FlowNodeType_Condition      FlowNodeType = "Condition"
	FlowNodeType_Input          FlowNodeType = "Input"
	FlowNodeType_Iterator       FlowNodeType = "Iterator"
	FlowNodeType_KnowledgeBase  FlowNodeType = "KnowledgeBase"
	FlowNodeType_LambdaFunction FlowNodeType = "LambdaFunction"
	FlowNodeType_Lex            FlowNodeType = "Lex"
	FlowNodeType_Output         FlowNodeType = "Output"
	FlowNodeType_Prompt         FlowNodeType = "Prompt"
	FlowNodeType_Retrieval      FlowNodeType = "Retrieval"
	FlowNodeType_Storage        FlowNodeType = "Storage"
)

type FlowStatus string

const (
	FlowStatus_Failed      FlowStatus = "Failed"
	FlowStatus_NotPrepared FlowStatus = "NotPrepared"
	FlowStatus_Prepared    FlowStatus = "Prepared"
	FlowStatus_Preparing   FlowStatus = "Preparing"
)

type FlowValidationSeverity string

const (
	FlowValidationSeverity_Error   FlowValidationSeverity = "Error"
	FlowValidationSeverity_Warning FlowValidationSeverity = "Warning"
)

type FlowValidationType string

const (
	FlowValidationType_CyclicConnection                FlowValidationType = "CyclicConnection"
	FlowValidationType_DuplicateConditionExpression    FlowValidationType = "DuplicateConditionExpression"
	FlowValidationType_DuplicateConnections            FlowValidationType = "DuplicateConnections"
	FlowValidationType_IncompatibleConnectionDataType  FlowValidationType = "IncompatibleConnectionDataType"
	FlowValidationType_MalformedConditionExpression    FlowValidationType = "MalformedConditionExpression"
	FlowValidationType_MalformedNodeInputExpression    FlowValidationType = "MalformedNodeInputExpression"
	FlowValidationType_MismatchedNodeInputType         FlowValidationType = "MismatchedNodeInputType"
	FlowValidationType_MismatchedNodeOutputType        FlowValidationType = "MismatchedNodeOutputType"
	FlowValidationType_MissingConnectionConfiguration  FlowValidationType = "MissingConnectionConfiguration"
	FlowValidationType_MissingDefaultCondition         FlowValidationType = "MissingDefaultCondition"
	FlowValidationType_MissingEndingNodes              FlowValidationType = "MissingEndingNodes"
	FlowValidationType_MissingNodeConfiguration        FlowValidationType = "MissingNodeConfiguration"
	FlowValidationType_MissingNodeInput                FlowValidationType = "MissingNodeInput"
	FlowValidationType_MissingNodeOutput               FlowValidationType = "MissingNodeOutput"
	FlowValidationType_MissingStartingNodes            FlowValidationType = "MissingStartingNodes"
	FlowValidationType_MultipleNodeInputConnections    FlowValidationType = "MultipleNodeInputConnections"
	FlowValidationType_UnfulfilledNodeInput            FlowValidationType = "UnfulfilledNodeInput"
	FlowValidationType_UnknownConnectionCondition      FlowValidationType = "UnknownConnectionCondition"
	FlowValidationType_UnknownConnectionSource         FlowValidationType = "UnknownConnectionSource"
	FlowValidationType_UnknownConnectionSourceOutput   FlowValidationType = "UnknownConnectionSourceOutput"
	FlowValidationType_UnknownConnectionTarget         FlowValidationType = "UnknownConnectionTarget"
	FlowValidationType_UnknownConnectionTargetInput    FlowValidationType = "UnknownConnectionTargetInput"
	FlowValidationType_UnreachableNode                 FlowValidationType = "UnreachableNode"
	FlowValidationType_UnsatisfiedConnectionConditions FlowValidationType = "UnsatisfiedConnectionConditions"
	FlowValidationType_Unspecified                     FlowValidationType = "Unspecified"
)

type IngestionJobFilterAttribute string

const (
	IngestionJobFilterAttribute_STATUS IngestionJobFilterAttribute = "STATUS"
)

type IngestionJobFilterOperator string

const (
	IngestionJobFilterOperator_EQ IngestionJobFilterOperator = "EQ"
)

type IngestionJobSortByAttribute string

const (
	IngestionJobSortByAttribute_STARTED_AT IngestionJobSortByAttribute = "STARTED_AT"
	IngestionJobSortByAttribute_STATUS     IngestionJobSortByAttribute = "STATUS"
)

type IngestionJobStatus string

const (
	IngestionJobStatus_COMPLETE    IngestionJobStatus = "COMPLETE"
	IngestionJobStatus_FAILED      IngestionJobStatus = "FAILED"
	IngestionJobStatus_IN_PROGRESS IngestionJobStatus = "IN_PROGRESS"
	IngestionJobStatus_STARTING    IngestionJobStatus = "STARTING"
	IngestionJobStatus_STOPPED     IngestionJobStatus = "STOPPED"
	IngestionJobStatus_STOPPING    IngestionJobStatus = "STOPPING"
)

type InlineContentType string

const (
	InlineContentType_BYTE InlineContentType = "BYTE"
	InlineContentType_TEXT InlineContentType = "TEXT"
)

type KnowledgeBaseState string

const (
	KnowledgeBaseState_DISABLED KnowledgeBaseState = "DISABLED"
	KnowledgeBaseState_ENABLED  KnowledgeBaseState = "ENABLED"
)

type KnowledgeBaseStatus string

const (
	KnowledgeBaseStatus_ACTIVE              KnowledgeBaseStatus = "ACTIVE"
	KnowledgeBaseStatus_CREATING            KnowledgeBaseStatus = "CREATING"
	KnowledgeBaseStatus_DELETE_UNSUCCESSFUL KnowledgeBaseStatus = "DELETE_UNSUCCESSFUL"
	KnowledgeBaseStatus_DELETING            KnowledgeBaseStatus = "DELETING"
	KnowledgeBaseStatus_FAILED              KnowledgeBaseStatus = "FAILED"
	KnowledgeBaseStatus_UPDATING            KnowledgeBaseStatus = "UPDATING"
)

type KnowledgeBaseStorageType string

const (
	KnowledgeBaseStorageType_MONGO_DB_ATLAS         KnowledgeBaseStorageType = "MONGO_DB_ATLAS"
	KnowledgeBaseStorageType_OPENSEARCH_SERVERLESS  KnowledgeBaseStorageType = "OPENSEARCH_SERVERLESS"
	KnowledgeBaseStorageType_PINECONE               KnowledgeBaseStorageType = "PINECONE"
	KnowledgeBaseStorageType_RDS                    KnowledgeBaseStorageType = "RDS"
	KnowledgeBaseStorageType_REDIS_ENTERPRISE_CLOUD KnowledgeBaseStorageType = "REDIS_ENTERPRISE_CLOUD"
)

type KnowledgeBaseType string

const (
	KnowledgeBaseType_VECTOR KnowledgeBaseType = "VECTOR"
)

type MemoryType string

const (
	MemoryType_SESSION_SUMMARY MemoryType = "SESSION_SUMMARY"
)

type MetadataSourceType string

const (
	MetadataSourceType_IN_LINE_ATTRIBUTE MetadataSourceType = "IN_LINE_ATTRIBUTE"
	MetadataSourceType_S3_LOCATION       MetadataSourceType = "S3_LOCATION"
)

type MetadataValueType string

const (
	MetadataValueType_BOOLEAN     MetadataValueType = "BOOLEAN"
	MetadataValueType_NUMBER      MetadataValueType = "NUMBER"
	MetadataValueType_STRING      MetadataValueType = "STRING"
	MetadataValueType_STRING_LIST MetadataValueType = "STRING_LIST"
)

type OrchestrationType string

const (
	OrchestrationType_CUSTOM_ORCHESTRATION OrchestrationType = "CUSTOM_ORCHESTRATION"
	OrchestrationType_DEFAULT              OrchestrationType = "DEFAULT"
)

type ParsingStrategy string

const (
	ParsingStrategy_BEDROCK_FOUNDATION_MODEL ParsingStrategy = "BEDROCK_FOUNDATION_MODEL"
)

type PromptState string

const (
	PromptState_DISABLED PromptState = "DISABLED"
	PromptState_ENABLED  PromptState = "ENABLED"
)

type PromptTemplateType string

const (
	PromptTemplateType_CHAT PromptTemplateType = "CHAT"
	PromptTemplateType_TEXT PromptTemplateType = "TEXT"
)

type PromptType string

const (
	PromptType_KNOWLEDGE_BASE_RESPONSE_GENERATION PromptType = "KNOWLEDGE_BASE_RESPONSE_GENERATION"
	PromptType_ORCHESTRATION                      PromptType = "ORCHESTRATION"
	PromptType_POST_PROCESSING                    PromptType = "POST_PROCESSING"
	PromptType_PRE_PROCESSING                     PromptType = "PRE_PROCESSING"
)

type RequireConfirmation string

const (
	RequireConfirmation_DISABLED RequireConfirmation = "DISABLED"
	RequireConfirmation_ENABLED  RequireConfirmation = "ENABLED"
)

type SalesforceAuthType string

const (
	SalesforceAuthType_OAUTH2_CLIENT_CREDENTIALS SalesforceAuthType = "OAUTH2_CLIENT_CREDENTIALS"
)

type SharePointAuthType string

const (
	SharePointAuthType_OAUTH2_CLIENT_CREDENTIALS SharePointAuthType = "OAUTH2_CLIENT_CREDENTIALS"
)

type SharePointHostType string

const (
	SharePointHostType_ONLINE SharePointHostType = "ONLINE"
)

type SortOrder string

const (
	SortOrder_ASCENDING  SortOrder = "ASCENDING"
	SortOrder_DESCENDING SortOrder = "DESCENDING"
)

type StepType string

const (
	StepType_POST_CHUNKING StepType = "POST_CHUNKING"
)

type Type string

const (
	Type_array   Type = "array"
	Type_boolean Type = "boolean"
	Type_integer Type = "integer"
	Type_number  Type = "number"
	Type_string  Type = "string"
)

type WebScopeType string

const (
	WebScopeType_HOST_ONLY  WebScopeType = "HOST_ONLY"
	WebScopeType_SUBDOMAINS WebScopeType = "SUBDOMAINS"
)
