//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionGroupExecutor) DeepCopyInto(out *ActionGroupExecutor) {
	*out = *in
	if in.Lambda != nil {
		in, out := &in.Lambda, &out.Lambda
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionGroupExecutor.
func (in *ActionGroupExecutor) DeepCopy() *ActionGroupExecutor {
	if in == nil {
		return nil
	}
	out := new(ActionGroupExecutor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionGroupSummary) DeepCopyInto(out *ActionGroupSummary) {
	*out = *in
	if in.ActionGroupID != nil {
		in, out := &in.ActionGroupID, &out.ActionGroupID
		*out = new(string)
		**out = **in
	}
	if in.ActionGroupName != nil {
		in, out := &in.ActionGroupName, &out.ActionGroupName
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionGroupSummary.
func (in *ActionGroupSummary) DeepCopy() *ActionGroupSummary {
	if in == nil {
		return nil
	}
	out := new(ActionGroupSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Agent) DeepCopyInto(out *Agent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Agent.
func (in *Agent) DeepCopy() *Agent {
	if in == nil {
		return nil
	}
	out := new(Agent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Agent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentActionGroup) DeepCopyInto(out *AgentActionGroup) {
	*out = *in
	if in.ActionGroupID != nil {
		in, out := &in.ActionGroupID, &out.ActionGroupID
		*out = new(string)
		**out = **in
	}
	if in.ActionGroupName != nil {
		in, out := &in.ActionGroupName, &out.ActionGroupName
		*out = new(string)
		**out = **in
	}
	if in.AgentID != nil {
		in, out := &in.AgentID, &out.AgentID
		*out = new(string)
		**out = **in
	}
	if in.AgentVersion != nil {
		in, out := &in.AgentVersion, &out.AgentVersion
		*out = new(string)
		**out = **in
	}
	if in.ClientToken != nil {
		in, out := &in.ClientToken, &out.ClientToken
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentActionGroup.
func (in *AgentActionGroup) DeepCopy() *AgentActionGroup {
	if in == nil {
		return nil
	}
	out := new(AgentActionGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentAlias) DeepCopyInto(out *AgentAlias) {
	*out = *in
	if in.AgentAliasName != nil {
		in, out := &in.AgentAliasName, &out.AgentAliasName
		*out = new(string)
		**out = **in
	}
	if in.AgentID != nil {
		in, out := &in.AgentID, &out.AgentID
		*out = new(string)
		**out = **in
	}
	if in.ClientToken != nil {
		in, out := &in.ClientToken, &out.ClientToken
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FailureReasons != nil {
		in, out := &in.FailureReasons, &out.FailureReasons
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentAlias.
func (in *AgentAlias) DeepCopy() *AgentAlias {
	if in == nil {
		return nil
	}
	out := new(AgentAlias)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentAliasHistoryEvent) DeepCopyInto(out *AgentAliasHistoryEvent) {
	*out = *in
	if in.EndDate != nil {
		in, out := &in.EndDate, &out.EndDate
		*out = (*in).DeepCopy()
	}
	if in.StartDate != nil {
		in, out := &in.StartDate, &out.StartDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentAliasHistoryEvent.
func (in *AgentAliasHistoryEvent) DeepCopy() *AgentAliasHistoryEvent {
	if in == nil {
		return nil
	}
	out := new(AgentAliasHistoryEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentAliasRoutingConfigurationListItem) DeepCopyInto(out *AgentAliasRoutingConfigurationListItem) {
	*out = *in
	if in.AgentVersion != nil {
		in, out := &in.AgentVersion, &out.AgentVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentAliasRoutingConfigurationListItem.
func (in *AgentAliasRoutingConfigurationListItem) DeepCopy() *AgentAliasRoutingConfigurationListItem {
	if in == nil {
		return nil
	}
	out := new(AgentAliasRoutingConfigurationListItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentAliasSummary) DeepCopyInto(out *AgentAliasSummary) {
	*out = *in
	if in.AgentAliasName != nil {
		in, out := &in.AgentAliasName, &out.AgentAliasName
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentAliasSummary.
func (in *AgentAliasSummary) DeepCopy() *AgentAliasSummary {
	if in == nil {
		return nil
	}
	out := new(AgentAliasSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCollaborator) DeepCopyInto(out *AgentCollaborator) {
	*out = *in
	if in.AgentID != nil {
		in, out := &in.AgentID, &out.AgentID
		*out = new(string)
		**out = **in
	}
	if in.AgentVersion != nil {
		in, out := &in.AgentVersion, &out.AgentVersion
		*out = new(string)
		**out = **in
	}
	if in.ClientToken != nil {
		in, out := &in.ClientToken, &out.ClientToken
		*out = new(string)
		**out = **in
	}
	if in.CollaboratorID != nil {
		in, out := &in.CollaboratorID, &out.CollaboratorID
		*out = new(string)
		**out = **in
	}
	if in.CollaboratorName != nil {
		in, out := &in.CollaboratorName, &out.CollaboratorName
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.LastUpdatedAt != nil {
		in, out := &in.LastUpdatedAt, &out.LastUpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCollaborator.
func (in *AgentCollaborator) DeepCopy() *AgentCollaborator {
	if in == nil {
		return nil
	}
	out := new(AgentCollaborator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCollaboratorSummary) DeepCopyInto(out *AgentCollaboratorSummary) {
	*out = *in
	if in.AgentID != nil {
		in, out := &in.AgentID, &out.AgentID
		*out = new(string)
		**out = **in
	}
	if in.AgentVersion != nil {
		in, out := &in.AgentVersion, &out.AgentVersion
		*out = new(string)
		**out = **in
	}
	if in.CollaboratorID != nil {
		in, out := &in.CollaboratorID, &out.CollaboratorID
		*out = new(string)
		**out = **in
	}
	if in.CollaboratorName != nil {
		in, out := &in.CollaboratorName, &out.CollaboratorName
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.LastUpdatedAt != nil {
		in, out := &in.LastUpdatedAt, &out.LastUpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCollaboratorSummary.
func (in *AgentCollaboratorSummary) DeepCopy() *AgentCollaboratorSummary {
	if in == nil {
		return nil
	}
	out := new(AgentCollaboratorSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentKnowledgeBase) DeepCopyInto(out *AgentKnowledgeBase) {
	*out = *in
	if in.AgentID != nil {
		in, out := &in.AgentID, &out.AgentID
		*out = new(string)
		**out = **in
	}
	if in.AgentVersion != nil {
		in, out := &in.AgentVersion, &out.AgentVersion
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.KnowledgeBaseID != nil {
		in, out := &in.KnowledgeBaseID, &out.KnowledgeBaseID
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentKnowledgeBase.
func (in *AgentKnowledgeBase) DeepCopy() *AgentKnowledgeBase {
	if in == nil {
		return nil
	}
	out := new(AgentKnowledgeBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentKnowledgeBaseSummary) DeepCopyInto(out *AgentKnowledgeBaseSummary) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.KnowledgeBaseID != nil {
		in, out := &in.KnowledgeBaseID, &out.KnowledgeBaseID
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentKnowledgeBaseSummary.
func (in *AgentKnowledgeBaseSummary) DeepCopy() *AgentKnowledgeBaseSummary {
	if in == nil {
		return nil
	}
	out := new(AgentKnowledgeBaseSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentList) DeepCopyInto(out *AgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Agent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentList.
func (in *AgentList) DeepCopy() *AgentList {
	if in == nil {
		return nil
	}
	out := new(AgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	if in.AgentCollaboration != nil {
		in, out := &in.AgentCollaboration, &out.AgentCollaboration
		*out = new(string)
		**out = **in
	}
	if in.AgentName != nil {
		in, out := &in.AgentName, &out.AgentName
		*out = new(string)
		**out = **in
	}
	if in.AgentResourceRoleARN != nil {
		in, out := &in.AgentResourceRoleARN, &out.AgentResourceRoleARN
		*out = new(string)
		**out = **in
	}
	if in.AgentResourceRoleRef != nil {
		in, out := &in.AgentResourceRoleRef, &out.AgentResourceRoleRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomOrchestration != nil {
		in, out := &in.CustomOrchestration, &out.CustomOrchestration
		*out = new(CustomOrchestration)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomerEncryptionKeyARN != nil {
		in, out := &in.CustomerEncryptionKeyARN, &out.CustomerEncryptionKeyARN
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FoundationModel != nil {
		in, out := &in.FoundationModel, &out.FoundationModel
		*out = new(string)
		**out = **in
	}
	if in.GuardrailConfiguration != nil {
		in, out := &in.GuardrailConfiguration, &out.GuardrailConfiguration
		*out = new(GuardrailConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.IdleSessionTTLInSeconds != nil {
		in, out := &in.IdleSessionTTLInSeconds, &out.IdleSessionTTLInSeconds
		*out = new(int64)
		**out = **in
	}
	if in.Instruction != nil {
		in, out := &in.Instruction, &out.Instruction
		*out = new(string)
		**out = **in
	}
	if in.MemoryConfiguration != nil {
		in, out := &in.MemoryConfiguration, &out.MemoryConfiguration
		*out = new(MemoryConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.OrchestrationType != nil {
		in, out := &in.OrchestrationType, &out.OrchestrationType
		*out = new(string)
		**out = **in
	}
	if in.PromptOverrideConfiguration != nil {
		in, out := &in.PromptOverrideConfiguration, &out.PromptOverrideConfiguration
		*out = new(PromptOverrideConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStatus) DeepCopyInto(out *AgentStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.AgentID != nil {
		in, out := &in.AgentID, &out.AgentID
		*out = new(string)
		**out = **in
	}
	if in.AgentStatus != nil {
		in, out := &in.AgentStatus, &out.AgentStatus
		*out = new(string)
		**out = **in
	}
	if in.AgentVersion != nil {
		in, out := &in.AgentVersion, &out.AgentVersion
		*out = new(string)
		**out = **in
	}
	if in.ClientToken != nil {
		in, out := &in.ClientToken, &out.ClientToken
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.FailureReasons != nil {
		in, out := &in.FailureReasons, &out.FailureReasons
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PreparedAt != nil {
		in, out := &in.PreparedAt, &out.PreparedAt
		*out = (*in).DeepCopy()
	}
	if in.RecommendedActions != nil {
		in, out := &in.RecommendedActions, &out.RecommendedActions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStatus.
func (in *AgentStatus) DeepCopy() *AgentStatus {
	if in == nil {
		return nil
	}
	out := new(AgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSummary) DeepCopyInto(out *AgentSummary) {
	*out = *in
	if in.AgentID != nil {
		in, out := &in.AgentID, &out.AgentID
		*out = new(string)
		**out = **in
	}
	if in.AgentName != nil {
		in, out := &in.AgentName, &out.AgentName
		*out = new(string)
		**out = **in
	}
	if in.AgentStatus != nil {
		in, out := &in.AgentStatus, &out.AgentStatus
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GuardrailConfiguration != nil {
		in, out := &in.GuardrailConfiguration, &out.GuardrailConfiguration
		*out = new(GuardrailConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.LatestAgentVersion != nil {
		in, out := &in.LatestAgentVersion, &out.LatestAgentVersion
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSummary.
func (in *AgentSummary) DeepCopy() *AgentSummary {
	if in == nil {
		return nil
	}
	out := new(AgentSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentVersion) DeepCopyInto(out *AgentVersion) {
	*out = *in
	if in.AgentARN != nil {
		in, out := &in.AgentARN, &out.AgentARN
		*out = new(string)
		**out = **in
	}
	if in.AgentCollaboration != nil {
		in, out := &in.AgentCollaboration, &out.AgentCollaboration
		*out = new(string)
		**out = **in
	}
	if in.AgentID != nil {
		in, out := &in.AgentID, &out.AgentID
		*out = new(string)
		**out = **in
	}
	if in.AgentName != nil {
		in, out := &in.AgentName, &out.AgentName
		*out = new(string)
		**out = **in
	}
	if in.AgentResourceRoleARN != nil {
		in, out := &in.AgentResourceRoleARN, &out.AgentResourceRoleARN
		*out = new(string)
		**out = **in
	}
	if in.AgentStatus != nil {
		in, out := &in.AgentStatus, &out.AgentStatus
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.CustomerEncryptionKeyARN != nil {
		in, out := &in.CustomerEncryptionKeyARN, &out.CustomerEncryptionKeyARN
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FailureReasons != nil {
		in, out := &in.FailureReasons, &out.FailureReasons
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.FoundationModel != nil {
		in, out := &in.FoundationModel, &out.FoundationModel
		*out = new(string)
		**out = **in
	}
	if in.GuardrailConfiguration != nil {
		in, out := &in.GuardrailConfiguration, &out.GuardrailConfiguration
		*out = new(GuardrailConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.IdleSessionTTLInSeconds != nil {
		in, out := &in.IdleSessionTTLInSeconds, &out.IdleSessionTTLInSeconds
		*out = new(int64)
		**out = **in
	}
	if in.Instruction != nil {
		in, out := &in.Instruction, &out.Instruction
		*out = new(string)
		**out = **in
	}
	if in.MemoryConfiguration != nil {
		in, out := &in.MemoryConfiguration, &out.MemoryConfiguration
		*out = new(MemoryConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.PromptOverrideConfiguration != nil {
		in, out := &in.PromptOverrideConfiguration, &out.PromptOverrideConfiguration
		*out = new(PromptOverrideConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.RecommendedActions != nil {
		in, out := &in.RecommendedActions, &out.RecommendedActions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentVersion.
func (in *AgentVersion) DeepCopy() *AgentVersion {
	if in == nil {
		return nil
	}
	out := new(AgentVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentVersionSummary) DeepCopyInto(out *AgentVersionSummary) {
	*out = *in
	if in.AgentName != nil {
		in, out := &in.AgentName, &out.AgentName
		*out = new(string)
		**out = **in
	}
	if in.AgentStatus != nil {
		in, out := &in.AgentStatus, &out.AgentStatus
		*out = new(string)
		**out = **in
	}
	if in.AgentVersion != nil {
		in, out := &in.AgentVersion, &out.AgentVersion
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GuardrailConfiguration != nil {
		in, out := &in.GuardrailConfiguration, &out.GuardrailConfiguration
		*out = new(GuardrailConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentVersionSummary.
func (in *AgentVersionSummary) DeepCopy() *AgentVersionSummary {
	if in == nil {
		return nil
	}
	out := new(AgentVersionSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Agent_SDK) DeepCopyInto(out *Agent_SDK) {
	*out = *in
	if in.AgentARN != nil {
		in, out := &in.AgentARN, &out.AgentARN
		*out = new(string)
		**out = **in
	}
	if in.AgentCollaboration != nil {
		in, out := &in.AgentCollaboration, &out.AgentCollaboration
		*out = new(string)
		**out = **in
	}
	if in.AgentID != nil {
		in, out := &in.AgentID, &out.AgentID
		*out = new(string)
		**out = **in
	}
	if in.AgentName != nil {
		in, out := &in.AgentName, &out.AgentName
		*out = new(string)
		**out = **in
	}
	if in.AgentResourceRoleARN != nil {
		in, out := &in.AgentResourceRoleARN, &out.AgentResourceRoleARN
		*out = new(string)
		**out = **in
	}
	if in.AgentStatus != nil {
		in, out := &in.AgentStatus, &out.AgentStatus
		*out = new(string)
		**out = **in
	}
	if in.AgentVersion != nil {
		in, out := &in.AgentVersion, &out.AgentVersion
		*out = new(string)
		**out = **in
	}
	if in.ClientToken != nil {
		in, out := &in.ClientToken, &out.ClientToken
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.CustomOrchestration != nil {
		in, out := &in.CustomOrchestration, &out.CustomOrchestration
		*out = new(CustomOrchestration)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomerEncryptionKeyARN != nil {
		in, out := &in.CustomerEncryptionKeyARN, &out.CustomerEncryptionKeyARN
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FailureReasons != nil {
		in, out := &in.FailureReasons, &out.FailureReasons
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.FoundationModel != nil {
		in, out := &in.FoundationModel, &out.FoundationModel
		*out = new(string)
		**out = **in
	}
	if in.GuardrailConfiguration != nil {
		in, out := &in.GuardrailConfiguration, &out.GuardrailConfiguration
		*out = new(GuardrailConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.IdleSessionTTLInSeconds != nil {
		in, out := &in.IdleSessionTTLInSeconds, &out.IdleSessionTTLInSeconds
		*out = new(int64)
		**out = **in
	}
	if in.Instruction != nil {
		in, out := &in.Instruction, &out.Instruction
		*out = new(string)
		**out = **in
	}
	if in.MemoryConfiguration != nil {
		in, out := &in.MemoryConfiguration, &out.MemoryConfiguration
		*out = new(MemoryConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.OrchestrationType != nil {
		in, out := &in.OrchestrationType, &out.OrchestrationType
		*out = new(string)
		**out = **in
	}
	if in.PreparedAt != nil {
		in, out := &in.PreparedAt, &out.PreparedAt
		*out = (*in).DeepCopy()
	}
	if in.PromptOverrideConfiguration != nil {
		in, out := &in.PromptOverrideConfiguration, &out.PromptOverrideConfiguration
		*out = new(PromptOverrideConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.RecommendedActions != nil {
		in, out := &in.RecommendedActions, &out.RecommendedActions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Agent_SDK.
func (in *Agent_SDK) DeepCopy() *Agent_SDK {
	if in == nil {
		return nil
	}
	out := new(Agent_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BedrockEmbeddingModelConfiguration) DeepCopyInto(out *BedrockEmbeddingModelConfiguration) {
	*out = *in
	if in.Dimensions != nil {
		in, out := &in.Dimensions, &out.Dimensions
		*out = new(int64)
		**out = **in
	}
	if in.EmbeddingDataType != nil {
		in, out := &in.EmbeddingDataType, &out.EmbeddingDataType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BedrockEmbeddingModelConfiguration.
func (in *BedrockEmbeddingModelConfiguration) DeepCopy() *BedrockEmbeddingModelConfiguration {
	if in == nil {
		return nil
	}
	out := new(BedrockEmbeddingModelConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteContentDoc) DeepCopyInto(out *ByteContentDoc) {
	*out = *in
	if in.MimeType != nil {
		in, out := &in.MimeType, &out.MimeType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteContentDoc.
func (in *ByteContentDoc) DeepCopy() *ByteContentDoc {
	if in == nil {
		return nil
	}
	out := new(ByteContentDoc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfluenceSourceConfiguration) DeepCopyInto(out *ConfluenceSourceConfiguration) {
	*out = *in
	if in.CredentialsSecretARN != nil {
		in, out := &in.CredentialsSecretARN, &out.CredentialsSecretARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfluenceSourceConfiguration.
func (in *ConfluenceSourceConfiguration) DeepCopy() *ConfluenceSourceConfiguration {
	if in == nil {
		return nil
	}
	out := new(ConfluenceSourceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentBlock) DeepCopyInto(out *ContentBlock) {
	*out = *in
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentBlock.
func (in *ContentBlock) DeepCopy() *ContentBlock {
	if in == nil {
		return nil
	}
	out := new(ContentBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CuratedQuery) DeepCopyInto(out *CuratedQuery) {
	*out = *in
	if in.NATuralLanguage != nil {
		in, out := &in.NATuralLanguage, &out.NATuralLanguage
		*out = new(string)
		**out = **in
	}
	if in.SQL != nil {
		in, out := &in.SQL, &out.SQL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CuratedQuery.
func (in *CuratedQuery) DeepCopy() *CuratedQuery {
	if in == nil {
		return nil
	}
	out := new(CuratedQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomDocumentIdentifier) DeepCopyInto(out *CustomDocumentIdentifier) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomDocumentIdentifier.
func (in *CustomDocumentIdentifier) DeepCopy() *CustomDocumentIdentifier {
	if in == nil {
		return nil
	}
	out := new(CustomDocumentIdentifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomOrchestration) DeepCopyInto(out *CustomOrchestration) {
	*out = *in
	if in.Executor != nil {
		in, out := &in.Executor, &out.Executor
		*out = new(OrchestrationExecutor)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomOrchestration.
func (in *CustomOrchestration) DeepCopy() *CustomOrchestration {
	if in == nil {
		return nil
	}
	out := new(CustomOrchestration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSource) DeepCopyInto(out *DataSource) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.DataSourceID != nil {
		in, out := &in.DataSourceID, &out.DataSourceID
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FailureReasons != nil {
		in, out := &in.FailureReasons, &out.FailureReasons
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.KnowledgeBaseID != nil {
		in, out := &in.KnowledgeBaseID, &out.KnowledgeBaseID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSource.
func (in *DataSource) DeepCopy() *DataSource {
	if in == nil {
		return nil
	}
	out := new(DataSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceSummary) DeepCopyInto(out *DataSourceSummary) {
	*out = *in
	if in.DataSourceID != nil {
		in, out := &in.DataSourceID, &out.DataSourceID
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.KnowledgeBaseID != nil {
		in, out := &in.KnowledgeBaseID, &out.KnowledgeBaseID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSummary.
func (in *DataSourceSummary) DeepCopy() *DataSourceSummary {
	if in == nil {
		return nil
	}
	out := new(DataSourceSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentIdentifier) DeepCopyInto(out *DocumentIdentifier) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Location)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentIdentifier.
func (in *DocumentIdentifier) DeepCopy() *DocumentIdentifier {
	if in == nil {
		return nil
	}
	out := new(DocumentIdentifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbeddingModelConfiguration) DeepCopyInto(out *EmbeddingModelConfiguration) {
	*out = *in
	if in.BedrockEmbeddingModelConfiguration != nil {
		in, out := &in.BedrockEmbeddingModelConfiguration, &out.BedrockEmbeddingModelConfiguration
		*out = new(BedrockEmbeddingModelConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbeddingModelConfiguration.
func (in *EmbeddingModelConfiguration) DeepCopy() *EmbeddingModelConfiguration {
	if in == nil {
		return nil
	}
	out := new(EmbeddingModelConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowAliasRoutingConfigurationListItem) DeepCopyInto(out *FlowAliasRoutingConfigurationListItem) {
	*out = *in
	if in.FlowVersion != nil {
		in, out := &in.FlowVersion, &out.FlowVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowAliasRoutingConfigurationListItem.
func (in *FlowAliasRoutingConfigurationListItem) DeepCopy() *FlowAliasRoutingConfigurationListItem {
	if in == nil {
		return nil
	}
	out := new(FlowAliasRoutingConfigurationListItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowAliasSummary) DeepCopyInto(out *FlowAliasSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowAliasSummary.
func (in *FlowAliasSummary) DeepCopy() *FlowAliasSummary {
	if in == nil {
		return nil
	}
	out := new(FlowAliasSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowSummary) DeepCopyInto(out *FlowSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowSummary.
func (in *FlowSummary) DeepCopy() *FlowSummary {
	if in == nil {
		return nil
	}
	out := new(FlowSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowVersionSummary) DeepCopyInto(out *FlowVersionSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowVersionSummary.
func (in *FlowVersionSummary) DeepCopy() *FlowVersionSummary {
	if in == nil {
		return nil
	}
	out := new(FlowVersionSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Function) DeepCopyInto(out *Function) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Function.
func (in *Function) DeepCopy() *Function {
	if in == nil {
		return nil
	}
	out := new(Function)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardrailConfiguration) DeepCopyInto(out *GuardrailConfiguration) {
	*out = *in
	if in.GuardrailIdentifier != nil {
		in, out := &in.GuardrailIdentifier, &out.GuardrailIdentifier
		*out = new(string)
		**out = **in
	}
	if in.GuardrailVersion != nil {
		in, out := &in.GuardrailVersion, &out.GuardrailVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardrailConfiguration.
func (in *GuardrailConfiguration) DeepCopy() *GuardrailConfiguration {
	if in == nil {
		return nil
	}
	out := new(GuardrailConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceConfiguration) DeepCopyInto(out *InferenceConfiguration) {
	*out = *in
	if in.MaximumLength != nil {
		in, out := &in.MaximumLength, &out.MaximumLength
		*out = new(int64)
		**out = **in
	}
	if in.StopSequences != nil {
		in, out := &in.StopSequences, &out.StopSequences
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Temperature != nil {
		in, out := &in.Temperature, &out.Temperature
		*out = new(float64)
		**out = **in
	}
	if in.TopK != nil {
		in, out := &in.TopK, &out.TopK
		*out = new(int64)
		**out = **in
	}
	if in.TopP != nil {
		in, out := &in.TopP, &out.TopP
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceConfiguration.
func (in *InferenceConfiguration) DeepCopy() *InferenceConfiguration {
	if in == nil {
		return nil
	}
	out := new(InferenceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestionJob) DeepCopyInto(out *IngestionJob) {
	*out = *in
	if in.DataSourceID != nil {
		in, out := &in.DataSourceID, &out.DataSourceID
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FailureReasons != nil {
		in, out := &in.FailureReasons, &out.FailureReasons
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IngestionJobID != nil {
		in, out := &in.IngestionJobID, &out.IngestionJobID
		*out = new(string)
		**out = **in
	}
	if in.KnowledgeBaseID != nil {
		in, out := &in.KnowledgeBaseID, &out.KnowledgeBaseID
		*out = new(string)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestionJob.
func (in *IngestionJob) DeepCopy() *IngestionJob {
	if in == nil {
		return nil
	}
	out := new(IngestionJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestionJobSummary) DeepCopyInto(out *IngestionJobSummary) {
	*out = *in
	if in.DataSourceID != nil {
		in, out := &in.DataSourceID, &out.DataSourceID
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IngestionJobID != nil {
		in, out := &in.IngestionJobID, &out.IngestionJobID
		*out = new(string)
		**out = **in
	}
	if in.KnowledgeBaseID != nil {
		in, out := &in.KnowledgeBaseID, &out.KnowledgeBaseID
		*out = new(string)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestionJobSummary.
func (in *IngestionJobSummary) DeepCopy() *IngestionJobSummary {
	if in == nil {
		return nil
	}
	out := new(IngestionJobSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntermediateStorage) DeepCopyInto(out *IntermediateStorage) {
	*out = *in
	if in.S3Location != nil {
		in, out := &in.S3Location, &out.S3Location
		*out = new(S3Location)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntermediateStorage.
func (in *IntermediateStorage) DeepCopy() *IntermediateStorage {
	if in == nil {
		return nil
	}
	out := new(IntermediateStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KendraKnowledgeBaseConfiguration) DeepCopyInto(out *KendraKnowledgeBaseConfiguration) {
	*out = *in
	if in.KendraIndexARN != nil {
		in, out := &in.KendraIndexARN, &out.KendraIndexARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KendraKnowledgeBaseConfiguration.
func (in *KendraKnowledgeBaseConfiguration) DeepCopy() *KendraKnowledgeBaseConfiguration {
	if in == nil {
		return nil
	}
	out := new(KendraKnowledgeBaseConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBase) DeepCopyInto(out *KnowledgeBase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBase.
func (in *KnowledgeBase) DeepCopy() *KnowledgeBase {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnowledgeBase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseConfiguration) DeepCopyInto(out *KnowledgeBaseConfiguration) {
	*out = *in
	if in.KendraKnowledgeBaseConfiguration != nil {
		in, out := &in.KendraKnowledgeBaseConfiguration, &out.KendraKnowledgeBaseConfiguration
		*out = new(KendraKnowledgeBaseConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.SQLKnowledgeBaseConfiguration != nil {
		in, out := &in.SQLKnowledgeBaseConfiguration, &out.SQLKnowledgeBaseConfiguration
		*out = new(SQLKnowledgeBaseConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.VectorKnowledgeBaseConfiguration != nil {
		in, out := &in.VectorKnowledgeBaseConfiguration, &out.VectorKnowledgeBaseConfiguration
		*out = new(VectorKnowledgeBaseConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseConfiguration.
func (in *KnowledgeBaseConfiguration) DeepCopy() *KnowledgeBaseConfiguration {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseDocumentDetail) DeepCopyInto(out *KnowledgeBaseDocumentDetail) {
	*out = *in
	if in.DataSourceID != nil {
		in, out := &in.DataSourceID, &out.DataSourceID
		*out = new(string)
		**out = **in
	}
	if in.KnowledgeBaseID != nil {
		in, out := &in.KnowledgeBaseID, &out.KnowledgeBaseID
		*out = new(string)
		**out = **in
	}
	if in.StatusReason != nil {
		in, out := &in.StatusReason, &out.StatusReason
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseDocumentDetail.
func (in *KnowledgeBaseDocumentDetail) DeepCopy() *KnowledgeBaseDocumentDetail {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseDocumentDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseFlowNodeConfiguration) DeepCopyInto(out *KnowledgeBaseFlowNodeConfiguration) {
	*out = *in
	if in.GuardrailConfiguration != nil {
		in, out := &in.GuardrailConfiguration, &out.GuardrailConfiguration
		*out = new(GuardrailConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseFlowNodeConfiguration.
func (in *KnowledgeBaseFlowNodeConfiguration) DeepCopy() *KnowledgeBaseFlowNodeConfiguration {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseFlowNodeConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseList) DeepCopyInto(out *KnowledgeBaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KnowledgeBase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseList.
func (in *KnowledgeBaseList) DeepCopy() *KnowledgeBaseList {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnowledgeBaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseSpec) DeepCopyInto(out *KnowledgeBaseSpec) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.KnowledgeBaseConfiguration != nil {
		in, out := &in.KnowledgeBaseConfiguration, &out.KnowledgeBaseConfiguration
		*out = new(KnowledgeBaseConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RoleARN != nil {
		in, out := &in.RoleARN, &out.RoleARN
		*out = new(string)
		**out = **in
	}
	if in.StorageConfiguration != nil {
		in, out := &in.StorageConfiguration, &out.StorageConfiguration
		*out = new(StorageConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseSpec.
func (in *KnowledgeBaseSpec) DeepCopy() *KnowledgeBaseSpec {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseStatus) DeepCopyInto(out *KnowledgeBaseStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.FailureReasons != nil {
		in, out := &in.FailureReasons, &out.FailureReasons
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.KnowledgeBaseID != nil {
		in, out := &in.KnowledgeBaseID, &out.KnowledgeBaseID
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseStatus.
func (in *KnowledgeBaseStatus) DeepCopy() *KnowledgeBaseStatus {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseSummary) DeepCopyInto(out *KnowledgeBaseSummary) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.KnowledgeBaseID != nil {
		in, out := &in.KnowledgeBaseID, &out.KnowledgeBaseID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseSummary.
func (in *KnowledgeBaseSummary) DeepCopy() *KnowledgeBaseSummary {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBase_SDK) DeepCopyInto(out *KnowledgeBase_SDK) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FailureReasons != nil {
		in, out := &in.FailureReasons, &out.FailureReasons
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.KnowledgeBaseARN != nil {
		in, out := &in.KnowledgeBaseARN, &out.KnowledgeBaseARN
		*out = new(string)
		**out = **in
	}
	if in.KnowledgeBaseConfiguration != nil {
		in, out := &in.KnowledgeBaseConfiguration, &out.KnowledgeBaseConfiguration
		*out = new(KnowledgeBaseConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.KnowledgeBaseID != nil {
		in, out := &in.KnowledgeBaseID, &out.KnowledgeBaseID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RoleARN != nil {
		in, out := &in.RoleARN, &out.RoleARN
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.StorageConfiguration != nil {
		in, out := &in.StorageConfiguration, &out.StorageConfiguration
		*out = new(StorageConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBase_SDK.
func (in *KnowledgeBase_SDK) DeepCopy() *KnowledgeBase_SDK {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBase_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LambdaFunctionFlowNodeConfiguration) DeepCopyInto(out *LambdaFunctionFlowNodeConfiguration) {
	*out = *in
	if in.LambdaARN != nil {
		in, out := &in.LambdaARN, &out.LambdaARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LambdaFunctionFlowNodeConfiguration.
func (in *LambdaFunctionFlowNodeConfiguration) DeepCopy() *LambdaFunctionFlowNodeConfiguration {
	if in == nil {
		return nil
	}
	out := new(LambdaFunctionFlowNodeConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryConfiguration) DeepCopyInto(out *MemoryConfiguration) {
	*out = *in
	if in.EnabledMemoryTypes != nil {
		in, out := &in.EnabledMemoryTypes, &out.EnabledMemoryTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SessionSummaryConfiguration != nil {
		in, out := &in.SessionSummaryConfiguration, &out.SessionSummaryConfiguration
		*out = new(SessionSummaryConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageDays != nil {
		in, out := &in.StorageDays, &out.StorageDays
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryConfiguration.
func (in *MemoryConfiguration) DeepCopy() *MemoryConfiguration {
	if in == nil {
		return nil
	}
	out := new(MemoryConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataAttributeValue) DeepCopyInto(out *MetadataAttributeValue) {
	*out = *in
	if in.BooleanValue != nil {
		in, out := &in.BooleanValue, &out.BooleanValue
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataAttributeValue.
func (in *MetadataAttributeValue) DeepCopy() *MetadataAttributeValue {
	if in == nil {
		return nil
	}
	out := new(MetadataAttributeValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAtlasConfiguration) DeepCopyInto(out *MongoDBAtlasConfiguration) {
	*out = *in
	if in.CollectionName != nil {
		in, out := &in.CollectionName, &out.CollectionName
		*out = new(string)
		**out = **in
	}
	if in.CredentialsSecretARN != nil {
		in, out := &in.CredentialsSecretARN, &out.CredentialsSecretARN
		*out = new(string)
		**out = **in
	}
	if in.DatabaseName != nil {
		in, out := &in.DatabaseName, &out.DatabaseName
		*out = new(string)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.EndpointServiceName != nil {
		in, out := &in.EndpointServiceName, &out.EndpointServiceName
		*out = new(string)
		**out = **in
	}
	if in.FieldMapping != nil {
		in, out := &in.FieldMapping, &out.FieldMapping
		*out = new(MongoDBAtlasFieldMapping)
		(*in).DeepCopyInto(*out)
	}
	if in.VectorIndexName != nil {
		in, out := &in.VectorIndexName, &out.VectorIndexName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAtlasConfiguration.
func (in *MongoDBAtlasConfiguration) DeepCopy() *MongoDBAtlasConfiguration {
	if in == nil {
		return nil
	}
	out := new(MongoDBAtlasConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAtlasFieldMapping) DeepCopyInto(out *MongoDBAtlasFieldMapping) {
	*out = *in
	if in.MetadataField != nil {
		in, out := &in.MetadataField, &out.MetadataField
		*out = new(string)
		**out = **in
	}
	if in.TextField != nil {
		in, out := &in.TextField, &out.TextField
		*out = new(string)
		**out = **in
	}
	if in.VectorField != nil {
		in, out := &in.VectorField, &out.VectorField
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAtlasFieldMapping.
func (in *MongoDBAtlasFieldMapping) DeepCopy() *MongoDBAtlasFieldMapping {
	if in == nil {
		return nil
	}
	out := new(MongoDBAtlasFieldMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchServerlessConfiguration) DeepCopyInto(out *OpenSearchServerlessConfiguration) {
	*out = *in
	if in.CollectionARN != nil {
		in, out := &in.CollectionARN, &out.CollectionARN
		*out = new(string)
		**out = **in
	}
	if in.FieldMapping != nil {
		in, out := &in.FieldMapping, &out.FieldMapping
		*out = new(OpenSearchServerlessFieldMapping)
		(*in).DeepCopyInto(*out)
	}
	if in.VectorIndexName != nil {
		in, out := &in.VectorIndexName, &out.VectorIndexName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchServerlessConfiguration.
func (in *OpenSearchServerlessConfiguration) DeepCopy() *OpenSearchServerlessConfiguration {
	if in == nil {
		return nil
	}
	out := new(OpenSearchServerlessConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchServerlessFieldMapping) DeepCopyInto(out *OpenSearchServerlessFieldMapping) {
	*out = *in
	if in.MetadataField != nil {
		in, out := &in.MetadataField, &out.MetadataField
		*out = new(string)
		**out = **in
	}
	if in.TextField != nil {
		in, out := &in.TextField, &out.TextField
		*out = new(string)
		**out = **in
	}
	if in.VectorField != nil {
		in, out := &in.VectorField, &out.VectorField
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchServerlessFieldMapping.
func (in *OpenSearchServerlessFieldMapping) DeepCopy() *OpenSearchServerlessFieldMapping {
	if in == nil {
		return nil
	}
	out := new(OpenSearchServerlessFieldMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrchestrationExecutor) DeepCopyInto(out *OrchestrationExecutor) {
	*out = *in
	if in.Lambda != nil {
		in, out := &in.Lambda, &out.Lambda
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrchestrationExecutor.
func (in *OrchestrationExecutor) DeepCopy() *OrchestrationExecutor {
	if in == nil {
		return nil
	}
	out := new(OrchestrationExecutor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterDetail) DeepCopyInto(out *ParameterDetail) {
	*out = *in
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterDetail.
func (in *ParameterDetail) DeepCopy() *ParameterDetail {
	if in == nil {
		return nil
	}
	out := new(ParameterDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PineconeConfiguration) DeepCopyInto(out *PineconeConfiguration) {
	*out = *in
	if in.ConnectionString != nil {
		in, out := &in.ConnectionString, &out.ConnectionString
		*out = new(string)
		**out = **in
	}
	if in.CredentialsSecretARN != nil {
		in, out := &in.CredentialsSecretARN, &out.CredentialsSecretARN
		*out = new(string)
		**out = **in
	}
	if in.FieldMapping != nil {
		in, out := &in.FieldMapping, &out.FieldMapping
		*out = new(PineconeFieldMapping)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PineconeConfiguration.
func (in *PineconeConfiguration) DeepCopy() *PineconeConfiguration {
	if in == nil {
		return nil
	}
	out := new(PineconeConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PineconeFieldMapping) DeepCopyInto(out *PineconeFieldMapping) {
	*out = *in
	if in.MetadataField != nil {
		in, out := &in.MetadataField, &out.MetadataField
		*out = new(string)
		**out = **in
	}
	if in.TextField != nil {
		in, out := &in.TextField, &out.TextField
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PineconeFieldMapping.
func (in *PineconeFieldMapping) DeepCopy() *PineconeFieldMapping {
	if in == nil {
		return nil
	}
	out := new(PineconeFieldMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptConfiguration) DeepCopyInto(out *PromptConfiguration) {
	*out = *in
	if in.BasePromptTemplate != nil {
		in, out := &in.BasePromptTemplate, &out.BasePromptTemplate
		*out = new(string)
		**out = **in
	}
	if in.FoundationModel != nil {
		in, out := &in.FoundationModel, &out.FoundationModel
		*out = new(string)
		**out = **in
	}
	if in.InferenceConfiguration != nil {
		in, out := &in.InferenceConfiguration, &out.InferenceConfiguration
		*out = new(InferenceConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ParserMode != nil {
		in, out := &in.ParserMode, &out.ParserMode
		*out = new(string)
		**out = **in
	}
	if in.PromptCreationMode != nil {
		in, out := &in.PromptCreationMode, &out.PromptCreationMode
		*out = new(string)
		**out = **in
	}
	if in.PromptState != nil {
		in, out := &in.PromptState, &out.PromptState
		*out = new(string)
		**out = **in
	}
	if in.PromptType != nil {
		in, out := &in.PromptType, &out.PromptType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptConfiguration.
func (in *PromptConfiguration) DeepCopy() *PromptConfiguration {
	if in == nil {
		return nil
	}
	out := new(PromptConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptFlowNodeConfiguration) DeepCopyInto(out *PromptFlowNodeConfiguration) {
	*out = *in
	if in.GuardrailConfiguration != nil {
		in, out := &in.GuardrailConfiguration, &out.GuardrailConfiguration
		*out = new(GuardrailConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptFlowNodeConfiguration.
func (in *PromptFlowNodeConfiguration) DeepCopy() *PromptFlowNodeConfiguration {
	if in == nil {
		return nil
	}
	out := new(PromptFlowNodeConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptModelInferenceConfiguration) DeepCopyInto(out *PromptModelInferenceConfiguration) {
	*out = *in
	if in.MaxTokens != nil {
		in, out := &in.MaxTokens, &out.MaxTokens
		*out = new(int64)
		**out = **in
	}
	if in.StopSequences != nil {
		in, out := &in.StopSequences, &out.StopSequences
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Temperature != nil {
		in, out := &in.Temperature, &out.Temperature
		*out = new(float64)
		**out = **in
	}
	if in.TopP != nil {
		in, out := &in.TopP, &out.TopP
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptModelInferenceConfiguration.
func (in *PromptModelInferenceConfiguration) DeepCopy() *PromptModelInferenceConfiguration {
	if in == nil {
		return nil
	}
	out := new(PromptModelInferenceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptOverrideConfiguration) DeepCopyInto(out *PromptOverrideConfiguration) {
	*out = *in
	if in.OverrideLambda != nil {
		in, out := &in.OverrideLambda, &out.OverrideLambda
		*out = new(string)
		**out = **in
	}
	if in.PromptConfigurations != nil {
		in, out := &in.PromptConfigurations, &out.PromptConfigurations
		*out = make([]*PromptConfiguration, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(PromptConfiguration)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptOverrideConfiguration.
func (in *PromptOverrideConfiguration) DeepCopy() *PromptOverrideConfiguration {
	if in == nil {
		return nil
	}
	out := new(PromptOverrideConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptSummary) DeepCopyInto(out *PromptSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptSummary.
func (in *PromptSummary) DeepCopy() *PromptSummary {
	if in == nil {
		return nil
	}
	out := new(PromptSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryGenerationColumn) DeepCopyInto(out *QueryGenerationColumn) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Inclusion != nil {
		in, out := &in.Inclusion, &out.Inclusion
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryGenerationColumn.
func (in *QueryGenerationColumn) DeepCopy() *QueryGenerationColumn {
	if in == nil {
		return nil
	}
	out := new(QueryGenerationColumn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryGenerationConfiguration) DeepCopyInto(out *QueryGenerationConfiguration) {
	*out = *in
	if in.ExecutionTimeoutSeconds != nil {
		in, out := &in.ExecutionTimeoutSeconds, &out.ExecutionTimeoutSeconds
		*out = new(int64)
		**out = **in
	}
	if in.GenerationContext != nil {
		in, out := &in.GenerationContext, &out.GenerationContext
		*out = new(QueryGenerationContext)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryGenerationConfiguration.
func (in *QueryGenerationConfiguration) DeepCopy() *QueryGenerationConfiguration {
	if in == nil {
		return nil
	}
	out := new(QueryGenerationConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryGenerationContext) DeepCopyInto(out *QueryGenerationContext) {
	*out = *in
	if in.CuratedQueries != nil {
		in, out := &in.CuratedQueries, &out.CuratedQueries
		*out = make([]*CuratedQuery, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(CuratedQuery)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tables != nil {
		in, out := &in.Tables, &out.Tables
		*out = make([]*QueryGenerationTable, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(QueryGenerationTable)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryGenerationContext.
func (in *QueryGenerationContext) DeepCopy() *QueryGenerationContext {
	if in == nil {
		return nil
	}
	out := new(QueryGenerationContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryGenerationTable) DeepCopyInto(out *QueryGenerationTable) {
	*out = *in
	if in.Columns != nil {
		in, out := &in.Columns, &out.Columns
		*out = make([]*QueryGenerationColumn, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(QueryGenerationColumn)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Inclusion != nil {
		in, out := &in.Inclusion, &out.Inclusion
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryGenerationTable.
func (in *QueryGenerationTable) DeepCopy() *QueryGenerationTable {
	if in == nil {
		return nil
	}
	out := new(QueryGenerationTable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RdsConfiguration) DeepCopyInto(out *RdsConfiguration) {
	*out = *in
	if in.CredentialsSecretARN != nil {
		in, out := &in.CredentialsSecretARN, &out.CredentialsSecretARN
		*out = new(string)
		**out = **in
	}
	if in.DatabaseName != nil {
		in, out := &in.DatabaseName, &out.DatabaseName
		*out = new(string)
		**out = **in
	}
	if in.FieldMapping != nil {
		in, out := &in.FieldMapping, &out.FieldMapping
		*out = new(RdsFieldMapping)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceARN != nil {
		in, out := &in.ResourceARN, &out.ResourceARN
		*out = new(string)
		**out = **in
	}
	if in.TableName != nil {
		in, out := &in.TableName, &out.TableName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RdsConfiguration.
func (in *RdsConfiguration) DeepCopy() *RdsConfiguration {
	if in == nil {
		return nil
	}
	out := new(RdsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RdsFieldMapping) DeepCopyInto(out *RdsFieldMapping) {
	*out = *in
	if in.MetadataField != nil {
		in, out := &in.MetadataField, &out.MetadataField
		*out = new(string)
		**out = **in
	}
	if in.PrimaryKeyField != nil {
		in, out := &in.PrimaryKeyField, &out.PrimaryKeyField
		*out = new(string)
		**out = **in
	}
	if in.TextField != nil {
		in, out := &in.TextField, &out.TextField
		*out = new(string)
		**out = **in
	}
	if in.VectorField != nil {
		in, out := &in.VectorField, &out.VectorField
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RdsFieldMapping.
func (in *RdsFieldMapping) DeepCopy() *RdsFieldMapping {
	if in == nil {
		return nil
	}
	out := new(RdsFieldMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisEnterpriseCloudConfiguration) DeepCopyInto(out *RedisEnterpriseCloudConfiguration) {
	*out = *in
	if in.CredentialsSecretARN != nil {
		in, out := &in.CredentialsSecretARN, &out.CredentialsSecretARN
		*out = new(string)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.FieldMapping != nil {
		in, out := &in.FieldMapping, &out.FieldMapping
		*out = new(RedisEnterpriseCloudFieldMapping)
		(*in).DeepCopyInto(*out)
	}
	if in.VectorIndexName != nil {
		in, out := &in.VectorIndexName, &out.VectorIndexName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisEnterpriseCloudConfiguration.
func (in *RedisEnterpriseCloudConfiguration) DeepCopy() *RedisEnterpriseCloudConfiguration {
	if in == nil {
		return nil
	}
	out := new(RedisEnterpriseCloudConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisEnterpriseCloudFieldMapping) DeepCopyInto(out *RedisEnterpriseCloudFieldMapping) {
	*out = *in
	if in.MetadataField != nil {
		in, out := &in.MetadataField, &out.MetadataField
		*out = new(string)
		**out = **in
	}
	if in.TextField != nil {
		in, out := &in.TextField, &out.TextField
		*out = new(string)
		**out = **in
	}
	if in.VectorField != nil {
		in, out := &in.VectorField, &out.VectorField
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisEnterpriseCloudFieldMapping.
func (in *RedisEnterpriseCloudFieldMapping) DeepCopy() *RedisEnterpriseCloudFieldMapping {
	if in == nil {
		return nil
	}
	out := new(RedisEnterpriseCloudFieldMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedshiftConfiguration) DeepCopyInto(out *RedshiftConfiguration) {
	*out = *in
	if in.QueryEngineConfiguration != nil {
		in, out := &in.QueryEngineConfiguration, &out.QueryEngineConfiguration
		*out = new(RedshiftQueryEngineConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.QueryGenerationConfiguration != nil {
		in, out := &in.QueryGenerationConfiguration, &out.QueryGenerationConfiguration
		*out = new(QueryGenerationConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageConfigurations != nil {
		in, out := &in.StorageConfigurations, &out.StorageConfigurations
		*out = make([]*RedshiftQueryEngineStorageConfiguration, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(RedshiftQueryEngineStorageConfiguration)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedshiftConfiguration.
func (in *RedshiftConfiguration) DeepCopy() *RedshiftConfiguration {
	if in == nil {
		return nil
	}
	out := new(RedshiftConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedshiftProvisionedAuthConfiguration) DeepCopyInto(out *RedshiftProvisionedAuthConfiguration) {
	*out = *in
	if in.DatabaseUser != nil {
		in, out := &in.DatabaseUser, &out.DatabaseUser
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UsernamePasswordSecretARN != nil {
		in, out := &in.UsernamePasswordSecretARN, &out.UsernamePasswordSecretARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedshiftProvisionedAuthConfiguration.
func (in *RedshiftProvisionedAuthConfiguration) DeepCopy() *RedshiftProvisionedAuthConfiguration {
	if in == nil {
		return nil
	}
	out := new(RedshiftProvisionedAuthConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedshiftProvisionedConfiguration) DeepCopyInto(out *RedshiftProvisionedConfiguration) {
	*out = *in
	if in.AuthConfiguration != nil {
		in, out := &in.AuthConfiguration, &out.AuthConfiguration
		*out = new(RedshiftProvisionedAuthConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterIdentifier != nil {
		in, out := &in.ClusterIdentifier, &out.ClusterIdentifier
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedshiftProvisionedConfiguration.
func (in *RedshiftProvisionedConfiguration) DeepCopy() *RedshiftProvisionedConfiguration {
	if in == nil {
		return nil
	}
	out := new(RedshiftProvisionedConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedshiftQueryEngineAWSDataCatalogStorageConfiguration) DeepCopyInto(out *RedshiftQueryEngineAWSDataCatalogStorageConfiguration) {
	*out = *in
	if in.TableNames != nil {
		in, out := &in.TableNames, &out.TableNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedshiftQueryEngineAWSDataCatalogStorageConfiguration.
func (in *RedshiftQueryEngineAWSDataCatalogStorageConfiguration) DeepCopy() *RedshiftQueryEngineAWSDataCatalogStorageConfiguration {
	if in == nil {
		return nil
	}
	out := new(RedshiftQueryEngineAWSDataCatalogStorageConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedshiftQueryEngineConfiguration) DeepCopyInto(out *RedshiftQueryEngineConfiguration) {
	*out = *in
	if in.ProvisionedConfiguration != nil {
		in, out := &in.ProvisionedConfiguration, &out.ProvisionedConfiguration
		*out = new(RedshiftProvisionedConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerlessConfiguration != nil {
		in, out := &in.ServerlessConfiguration, &out.ServerlessConfiguration
		*out = new(RedshiftServerlessConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedshiftQueryEngineConfiguration.
func (in *RedshiftQueryEngineConfiguration) DeepCopy() *RedshiftQueryEngineConfiguration {
	if in == nil {
		return nil
	}
	out := new(RedshiftQueryEngineConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedshiftQueryEngineRedshiftStorageConfiguration) DeepCopyInto(out *RedshiftQueryEngineRedshiftStorageConfiguration) {
	*out = *in
	if in.DatabaseName != nil {
		in, out := &in.DatabaseName, &out.DatabaseName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedshiftQueryEngineRedshiftStorageConfiguration.
func (in *RedshiftQueryEngineRedshiftStorageConfiguration) DeepCopy() *RedshiftQueryEngineRedshiftStorageConfiguration {
	if in == nil {
		return nil
	}
	out := new(RedshiftQueryEngineRedshiftStorageConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedshiftQueryEngineStorageConfiguration) DeepCopyInto(out *RedshiftQueryEngineStorageConfiguration) {
	*out = *in
	if in.AWSDataCatalogConfiguration != nil {
		in, out := &in.AWSDataCatalogConfiguration, &out.AWSDataCatalogConfiguration
		*out = new(RedshiftQueryEngineAWSDataCatalogStorageConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.RedshiftConfiguration != nil {
		in, out := &in.RedshiftConfiguration, &out.RedshiftConfiguration
		*out = new(RedshiftQueryEngineRedshiftStorageConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedshiftQueryEngineStorageConfiguration.
func (in *RedshiftQueryEngineStorageConfiguration) DeepCopy() *RedshiftQueryEngineStorageConfiguration {
	if in == nil {
		return nil
	}
	out := new(RedshiftQueryEngineStorageConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedshiftServerlessAuthConfiguration) DeepCopyInto(out *RedshiftServerlessAuthConfiguration) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UsernamePasswordSecretARN != nil {
		in, out := &in.UsernamePasswordSecretARN, &out.UsernamePasswordSecretARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedshiftServerlessAuthConfiguration.
func (in *RedshiftServerlessAuthConfiguration) DeepCopy() *RedshiftServerlessAuthConfiguration {
	if in == nil {
		return nil
	}
	out := new(RedshiftServerlessAuthConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedshiftServerlessConfiguration) DeepCopyInto(out *RedshiftServerlessConfiguration) {
	*out = *in
	if in.AuthConfiguration != nil {
		in, out := &in.AuthConfiguration, &out.AuthConfiguration
		*out = new(RedshiftServerlessAuthConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkgroupARN != nil {
		in, out := &in.WorkgroupARN, &out.WorkgroupARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedshiftServerlessConfiguration.
func (in *RedshiftServerlessConfiguration) DeepCopy() *RedshiftServerlessConfiguration {
	if in == nil {
		return nil
	}
	out := new(RedshiftServerlessConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Content) DeepCopyInto(out *S3Content) {
	*out = *in
	if in.S3Location != nil {
		in, out := &in.S3Location, &out.S3Location
		*out = new(S3Location)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Content.
func (in *S3Content) DeepCopy() *S3Content {
	if in == nil {
		return nil
	}
	out := new(S3Content)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Location) DeepCopyInto(out *S3Location) {
	*out = *in
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Location.
func (in *S3Location) DeepCopy() *S3Location {
	if in == nil {
		return nil
	}
	out := new(S3Location)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQLKnowledgeBaseConfiguration) DeepCopyInto(out *SQLKnowledgeBaseConfiguration) {
	*out = *in
	if in.RedshiftConfiguration != nil {
		in, out := &in.RedshiftConfiguration, &out.RedshiftConfiguration
		*out = new(RedshiftConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQLKnowledgeBaseConfiguration.
func (in *SQLKnowledgeBaseConfiguration) DeepCopy() *SQLKnowledgeBaseConfiguration {
	if in == nil {
		return nil
	}
	out := new(SQLKnowledgeBaseConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SalesforceSourceConfiguration) DeepCopyInto(out *SalesforceSourceConfiguration) {
	*out = *in
	if in.CredentialsSecretARN != nil {
		in, out := &in.CredentialsSecretARN, &out.CredentialsSecretARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SalesforceSourceConfiguration.
func (in *SalesforceSourceConfiguration) DeepCopy() *SalesforceSourceConfiguration {
	if in == nil {
		return nil
	}
	out := new(SalesforceSourceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerSideEncryptionConfiguration) DeepCopyInto(out *ServerSideEncryptionConfiguration) {
	*out = *in
	if in.KMSKeyARN != nil {
		in, out := &in.KMSKeyARN, &out.KMSKeyARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerSideEncryptionConfiguration.
func (in *ServerSideEncryptionConfiguration) DeepCopy() *ServerSideEncryptionConfiguration {
	if in == nil {
		return nil
	}
	out := new(ServerSideEncryptionConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionSummaryConfiguration) DeepCopyInto(out *SessionSummaryConfiguration) {
	*out = *in
	if in.MaxRecentSessions != nil {
		in, out := &in.MaxRecentSessions, &out.MaxRecentSessions
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionSummaryConfiguration.
func (in *SessionSummaryConfiguration) DeepCopy() *SessionSummaryConfiguration {
	if in == nil {
		return nil
	}
	out := new(SessionSummaryConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharePointSourceConfiguration) DeepCopyInto(out *SharePointSourceConfiguration) {
	*out = *in
	if in.CredentialsSecretARN != nil {
		in, out := &in.CredentialsSecretARN, &out.CredentialsSecretARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharePointSourceConfiguration.
func (in *SharePointSourceConfiguration) DeepCopy() *SharePointSourceConfiguration {
	if in == nil {
		return nil
	}
	out := new(SharePointSourceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfiguration) DeepCopyInto(out *StorageConfiguration) {
	*out = *in
	if in.MongoDBAtlasConfiguration != nil {
		in, out := &in.MongoDBAtlasConfiguration, &out.MongoDBAtlasConfiguration
		*out = new(MongoDBAtlasConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.OpensearchServerlessConfiguration != nil {
		in, out := &in.OpensearchServerlessConfiguration, &out.OpensearchServerlessConfiguration
		*out = new(OpenSearchServerlessConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.PineconeConfiguration != nil {
		in, out := &in.PineconeConfiguration, &out.PineconeConfiguration
		*out = new(PineconeConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.RdsConfiguration != nil {
		in, out := &in.RdsConfiguration, &out.RdsConfiguration
		*out = new(RdsConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.RedisEnterpriseCloudConfiguration != nil {
		in, out := &in.RedisEnterpriseCloudConfiguration, &out.RedisEnterpriseCloudConfiguration
		*out = new(RedisEnterpriseCloudConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfiguration.
func (in *StorageConfiguration) DeepCopy() *StorageConfiguration {
	if in == nil {
		return nil
	}
	out := new(StorageConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupplementalDataStorageConfiguration) DeepCopyInto(out *SupplementalDataStorageConfiguration) {
	*out = *in
	if in.StorageLocations != nil {
		in, out := &in.StorageLocations, &out.StorageLocations
		*out = make([]*SupplementalDataStorageLocation, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(SupplementalDataStorageLocation)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupplementalDataStorageConfiguration.
func (in *SupplementalDataStorageConfiguration) DeepCopy() *SupplementalDataStorageConfiguration {
	if in == nil {
		return nil
	}
	out := new(SupplementalDataStorageConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupplementalDataStorageLocation) DeepCopyInto(out *SupplementalDataStorageLocation) {
	*out = *in
	if in.S3Location != nil {
		in, out := &in.S3Location, &out.S3Location
		*out = new(S3Location)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupplementalDataStorageLocation.
func (in *SupplementalDataStorageLocation) DeepCopy() *SupplementalDataStorageLocation {
	if in == nil {
		return nil
	}
	out := new(SupplementalDataStorageLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformationLambdaConfiguration) DeepCopyInto(out *TransformationLambdaConfiguration) {
	*out = *in
	if in.LambdaARN != nil {
		in, out := &in.LambdaARN, &out.LambdaARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformationLambdaConfiguration.
func (in *TransformationLambdaConfiguration) DeepCopy() *TransformationLambdaConfiguration {
	if in == nil {
		return nil
	}
	out := new(TransformationLambdaConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VectorKnowledgeBaseConfiguration) DeepCopyInto(out *VectorKnowledgeBaseConfiguration) {
	*out = *in
	if in.EmbeddingModelARN != nil {
		in, out := &in.EmbeddingModelARN, &out.EmbeddingModelARN
		*out = new(string)
		**out = **in
	}
	if in.EmbeddingModelConfiguration != nil {
		in, out := &in.EmbeddingModelConfiguration, &out.EmbeddingModelConfiguration
		*out = new(EmbeddingModelConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.SupplementalDataStorageConfiguration != nil {
		in, out := &in.SupplementalDataStorageConfiguration, &out.SupplementalDataStorageConfiguration
		*out = new(SupplementalDataStorageConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VectorKnowledgeBaseConfiguration.
func (in *VectorKnowledgeBaseConfiguration) DeepCopy() *VectorKnowledgeBaseConfiguration {
	if in == nil {
		return nil
	}
	out := new(VectorKnowledgeBaseConfiguration)
	in.DeepCopyInto(out)
	return out
}
